# Development environment override
services:
  dominus-api:
    build:
      context: api
      target: frankenphp_dev
    environment:
      FRANKENPHP_WORKER_CONFIG: watch
      MERCURE_EXTRA_DIRECTIVES: demo
      XDEBUG_MODE: "${XDEBUG_MODE:-off}"
      APP_ENV: "${APP_ENV:-dev}"
      COMPOSE_PROJECT_NAME: "${COMPOSE_PROJECT_NAME:-dominus-api}"
    extra_hosts:
      # Ensure that host.docker.internal is correctly defined on Linux
      - host.docker.internal:host-gateway
    tty: true
    volumes:
      - ./api/frankenphp/Caddyfile:/etc/caddy/Caddyfile
